version: '3.4'

x-base:
  &base
  networks:
    - docker_net
  restart: always


services:
  postgres:
    << : *base
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
    docker_net:
        driver: bridge
